
-- ตาราง authen
CREATE TABLE authen (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(32) NOT NULL UNIQUE,
  password VARCHAR(200) NOT NULL,
  role_id INT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ตาราง room
CREATE TABLE room (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(32) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE queue (
  id INT AUTO_INCREMENT PRIMARY KEY,
  reason VARCHAR(200) NOT NULL,
  room_id INT NOT NULL,
  authen_id INT NOT NULL,
  status_id INT NOT NULL,
  at DATETIME NOT NULL, 
  FOREIGN KEY (room_id) REFERENCES room(id) ON DELETE CASCADE ON UPDATE CASCADE,
  FOREIGN KEY (authen_id) REFERENCES authen(id) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
